[workspace]
members = [
    "crates/libs/*",
    "crates/apps/*",
    "crates/tools/*",
    "crates/examples/*",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["oneofthezombies"]
repository = "https://github.com/oneofthezombies/kill-tree"
license = "MIT"
