[package]
name = "kill-tree-cli"
version = "0.1.0"
authors = ["oneofthezombies"]
description = "Multi-platform library that kill the process also with all child processes."
edition = "2021"

[dependencies]
kill-tree = { path = "../lib" }
clap = { version = "4.4.18", features = ["cargo"] }
