[package]
name = "example-readme"
version = "0.0.0"
edition.workspace = true

[dependencies]
kill_tree = { path = "../../libs/kill_tree" }

[[bin]]
name = "kill_tree"
path = "src/kill_tree.rs"

[[bin]]
name = "kill_tree_sigkill"
path = "src/kill_tree_sigkill.rs"
