name: Build, Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'
    # - uses: dtolnay/rust-toolchain@stable
    - name: cargo check
      run: cargo check --workspace
    - name: cargo clippy
      run: cargo clippy -- -D clippy::pedantic
    - name: cargo fmt
      run: cargo fmt -- --check
    - name: cargo test
      run: cargo test --workspace
