name: Lint, Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-build-test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - runner: ubuntu-latest
            platform: linux
          - runner: windows-latest
            platform: windows
          - runner: macos-latest
            platform: macos

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'
    - name: Check
      run: cargo run --package tool-dev -- check
    - name: Clippy
      run: cargo run --package tool-dev -- clippy
    - name: Format
      run: cargo run --package tool-dev -- fmt
    - name: Build
      run: cargo run --package tool-dev -- build ${{ matrix.platform }}
    - name: Test
      run: cargo run --package tool-dev -- test ${{ matrix.platform }}
