name: Lint, Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'
    - name: check
      run: cargo run --package tool-dev -- check
    - name: clippy
      run: cargo run --package tool-dev -- clippy
    - name: fmt
      run: cargo run --package tool-dev -- fmt
    - name: build
      run: cargo run --package tool-dev -- build linux
    - name: test
      run: cargo run --package tool-dev -- test linux
